name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - run: npm ci
    - run: npm run build-storybook

    - name: 'upload'
      uses: actions/upload-pages-artifact@v3
      with: 
        path: ./storybook-static

    - id: deploy
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        token: ${{ github.token }}
